# Generated by Django 2.2.5 on 2019-12-08 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre Hospital', max_length=60)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitales',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre Paciente', max_length=60)),
                ('edad', models.PositiveIntegerField(help_text='Edad', verbose_name='Edad')),
                ('n_hist_clinica', models.PositiveIntegerField(help_text='Número historia clínica', verbose_name='Número historia clínica')),
                ('hospitales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hospital')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ('pk',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Panciano',
            fields=[
                ('paciente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Paciente')),
                ('tiene_dieta', models.BooleanField(default=False, help_text='Tiene dieta')),
            ],
            options={
                'verbose_name': 'Panciano',
                'verbose_name_plural': 'Pancianos',
                'ordering': ('pk',),
                'abstract': False,
            },
            bases=('main.paciente',),
        ),
        migrations.CreateModel(
            name='Pjoven',
            fields=[
                ('paciente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Paciente')),
                ('fumador', models.BooleanField(default=False, help_text='fumador')),
            ],
            options={
                'verbose_name': 'Pjoven',
                'verbose_name_plural': 'Pjovenes',
                'ordering': ('pk',),
                'abstract': False,
            },
            bases=('main.paciente',),
        ),
        migrations.CreateModel(
            name='Pnino',
            fields=[
                ('paciente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Paciente')),
                ('rel_peso_estatura', models.PositiveIntegerField(verbose_name='Relación peso/estatura')),
            ],
            options={
                'verbose_name': 'Pnino',
                'verbose_name_plural': 'Pninos',
                'ordering': ('pk',),
                'abstract': False,
            },
            bases=('main.paciente',),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_consulta', models.PositiveIntegerField(verbose_name='ID consulta')),
                ('cantidad_pacientes', models.PositiveIntegerField(verbose_name='Cantidad pacientes')),
                ('nombre_especialista', models.CharField(help_text='Nombre especialista', max_length=60)),
                ('tipo_consulta', models.CharField(choices=[('PED', 'Pediatría'), ('URG', 'Urgencia'), ('CGI', 'Consulta General Integral')], max_length=50, verbose_name='Tipo consulta')),
                ('estado', models.CharField(choices=[('OCU', 'Ocupada'), ('ESP', 'Espera de atención')], max_length=50, verbose_name='Estado')),
                ('hospitales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hospital')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ('pk',),
            },
        ),
    ]
