# Generated by Django 2.2.5 on 2019-12-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191208_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='nombre_especialista',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(help_text='Edad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='n_hist_clinica',
            field=models.PositiveIntegerField(help_text='Número historia clínica'),
        ),
        migrations.AlterField(
            model_name='pnino',
            name='rel_peso_estatura',
            field=models.PositiveIntegerField(help_text='Relación peso/estatura'),
        ),
    ]
