# Generated by Django 2.2.5 on 2019-12-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_paciente_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panciano',
            name='tiene_dieta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pjoven',
            name='fumador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pnino',
            name='rel_peso_estatura',
            field=models.PositiveIntegerField(),
        ),
    ]
